### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Robert3141** [sruusk/simflow#1]
I love this webapp. But I just thought I'd make you aware that your github pages is not currently availiable on either of the simflow domains:
[simflow.webflow.io/](simflow.webflow.io)
[simflow.app/](simflow.app)
Also, the discord link at the bottom of the page has expired

**Comment by sruusk** [comment]
As explained in the readme, this is just a reproduction of the simflow site and I have nothing to do with the original.
I made this because the original was made with webflow and therefore is locked down to that platform.
This is also modeled after the older version of simflow. [Demo](https://sruusk.github.io/simflow/)

I have no idea why they shut down the site, probably because hosting it on webflow costs ~$18/month. 
They also deleted the discord server so the invite won't work anymore.

**Comment by Robert3141** [comment]
Thanks for the explainer and great work on the reproduction
